### PR TITLE
Update AdminPanelProvider.php

### PR DESCRIPTION
**Pull request by MrRobotIsHere**

### CODE REVIEW

**Comment by gomzyakov** [comment]
@MrRobotIsHere  Hello!

I accepted your edits with the password reset form in PR https://github.com/gomzyakov/laravel-blog/pull/208, but there is no need for the admin user registration form. Only another admin can add new admins.

This is done for security reasons. Do you agree?

**Comment by MrRobotIsHere** [comment]
> @MrRobotIsHere  Hello!
> 
> I accepted your edits with the password reset form in PR https://github.com/gomzyakov/laravel-blog/pull/208, but there is no need for the admin user registration form. Only another admin can add new admins.
> 
> This is done for security reasons. Do you agree?

Yeah it's ok 👌🏻

**Comment by MrRobotIsHere** [comment]
Can I have your phone number if I have some questions to ask you my question?

**Comment by gomzyakov** [comment]
@MrRobotIsHere 

You can always ask any questions in [discussions](https://github.com/gomzyakov/laravel-blog/discussions) ;)

**Comment by MrRobotIsHere** [comment]
> @MrRobotIsHere 
> 
> You can always ask any questions in [discussions](https://github.com/gomzyakov/laravel-blog/discussions) 😉

Alright bro 👍🏻😊

**Comment by MrRobotIsHere** [comment]
I'll be happy if you follow me😁

**Pull request closed without merging**
